-- ============================================================
-- SQL SCRIPT: Soft Delete & Makanan Refactoring
-- PENTING: JALANKAN SCRIPT INI DI SUPABASE SQL EDITOR
-- ============================================================

-- 1. MUSNAHKAN TABEL MAKANAN LAMA
-- (Otomatis menghapus referensi jika menggunakan CONSTRAINT)
DROP TABLE IF EXISTS makanan_item CASCADE;
DROP TABLE IF EXISTS makanan_porsi CASCADE;
DROP TABLE IF EXISTS makanan_induk CASCADE;

-- 2. BUAT TABEL MAKANAN BARU (HIRARKI INDUK -> PORSI)
CREATE TABLE makanan_induk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode VARCHAR(50),
  nama VARCHAR(255) NOT NULL,
  kategori_id INT REFERENCES kategori_makanan(id) ON DELETE SET NULL,
  keterangan TEXT,
  foto TEXT,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE makanan_porsi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  makanan_id BIGINT REFERENCES makanan_induk(id) ON DELETE CASCADE,
  kode_porsi VARCHAR(50),
  nama_porsi VARCHAR(255) NOT NULL, -- (Besar Porsi: misal '1 Porsi Sedang')
  berat_gram DECIMAL,
  energi DECIMAL DEFAULT 0,
  protein DECIMAL DEFAULT 0,
  lemak DECIMAL DEFAULT 0,
  karbohidrat DECIMAL DEFAULT 0,
  serat DECIMAL DEFAULT 0,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. PERBARUI TABEL FOOD RECORDS
-- Kita biarkan nilai masa lalu, hanya tambahkan porsi_id
ALTER TABLE food_records ADD COLUMN IF NOT EXISTS porsi_id BIGINT REFERENCES makanan_porsi(id) ON DELETE SET NULL;
ALTER TABLE food_records ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;

-- Hapus kolom jumlah_urt yang sudah tidak diperlukan (opsional, tapi aman)
-- ALTER TABLE food_records DROP COLUMN jumlah_urt;

-- 4. TAMBAHKAN FLAG DELETED DI TABEL LAINNYA
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE analisis_gizi ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE kebutuhan_gizi ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE access_logs ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;


-- ============================================================
-- SEED DATA PERCONTOHAN (OPTIONAL)
-- Sesuai format Excel baru:
-- ============================================================
INSERT INTO makanan_induk (id, kode, nama, kategori_id, keterangan) VALUES
  (1, 'A.1', 'Nasi Putih', 2, 'Olahan (AP001)'),
  (2, 'A.2', 'Ayam Goreng', 3, 'Gorengan')
ON CONFLICT (id) DO UPDATE SET
  kode = EXCLUDED.kode,
  nama = EXCLUDED.nama,
  kategori_id = EXCLUDED.kategori_id,
  keterangan = EXCLUDED.keterangan;

-- Sesuaikan auto increment sekuens
SELECT setval('makanan_induk_id_seq', (SELECT MAX(id) FROM makanan_induk));

INSERT INTO makanan_porsi (makanan_id, kode_porsi, nama_porsi, berat_gram, energi, protein, lemak, karbohidrat, serat) VALUES
  -- Nasi Putih Porsi A
  (1, 'A.1.A', '1 Porsi Besar', 300, 540, 9, 0.9, 119.4, 0.6),
  (1, 'A.1.B', '1 Porsi Sedang', 200, 360, 6, 0.6, 79.6, 0.4),
  (1, 'A.1.C', '1 Porsi Kecil', 100, 180, 3, 0.3, 39.8, 0.2),
  (1, 'A.2.A', '1 Ctg Rice Cooker', 50, 90, 1.5, 0.15, 19.9, 0.1),
  (1, 'A.2.D', '1 Sdm', 15, 27, 0.45, 0.045, 5.97, 0.03),
  
  -- Ayam Goreng (Contoh saja, nilai gizi random)
  (2, 'A.2.1', '1 Potong Besar', 120, 250, 20, 15, 0, 0),
  (2, 'A.2.2', '1 Potong Kecil', 80, 180, 15, 10, 0, 0);

